### ISSUE TITLE
wp-config file not found

### ISSUE THREAD

**Issue by perVron** [elegantthemes/create-divi-extension#283]
### Problem Description
Error: Unable to locate wp-config.php!
    at new WPConfig (C:\xampp\htdocs\myGarage\wp-content\plugins\new_module\node_modules\divi-dev-utils\WPConfig.js:13:13)
    at Object.<anonymous> (C:\xampp\htdocs\myGarage\wp-content\plugins\new_module\node_modules\divi-dev-utils\WPConfig.js:
79:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\xampp\htdocs\myGarage\wp-content\plugins\new_module\node_modules\divi-scripts\scripts\start.
js:47:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693

**Comment by numerosata** [comment]
I've noticed too that at some point wp-config.php was zeroed.
