### ISSUE TITLE
Error: spawn git ENOENT while creating extension

### ISSUE THREAD

**Issue by DevSar1992** [elegantthemes/create-divi-extension#329]
Hey there,

I'm quite new to Node.js and  can't figure out, what went wrong. I would like to create a new extension with `npx create-divi-extension my-extension` and it doesn't work. This is, what the error log says:

```
npx: installed 176 in 21.117s

Creating a new Divi extension in C:\Users\Prime\devspace\wp-content\plugins\my-extension.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and divi-scripts...

➤ YN0000: ┌ Resolution step
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at r (C:\Users\Prime\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:24:316321)
    at i (C:\Users\Prime\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:24:316492)
    at ChildProcess.e.emit (C:\Users\Prime\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:24:316633)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess.e.emit (C:\Users\Prime\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js:24:316654)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'ls-remote',
    '--refs',
    'https://github.com/elegantthemes/grunt-po2mo.git'
  ]
}

Aborting installation.
  yarnpkg add --exact react react-dom divi-scripts --cwd C:\Users\Prime\devspace\wp-content\plugins\my-extension has failed.

Deleting generated file... package.json
Done.
```

### Steps To Reproduce
1. I installed Docker Desktop for Windows 10 Pro
2. I set up the development enviroment
3. I installed Node.js and Yarn
4. I tried to create extension - and it doesnt work.

Does anybody has any idea, what went wrong?

Thanks so much!

**Comment by amunrarara** [comment]
I am also having the same issue.
