### ISSUE TITLE
Source-map not working

### ISSUE THREAD

**Issue by danielvoelk** [elegantthemes/create-divi-extension#356]
### Problem Description
After I use "npm start build" and debug with Chrome and VS Code I get following error:

```
SourceMaps.getMapForGeneratedPath: exception while processing path: http://localhost/divifilter/wp-content/themes/Divi/js/custom.unified.js?ver=4.4.3, sourcemap: custom.unified.js.map

SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (c:\Users\danie\.vscode\extensions\msjsdiag.debugger-for-chrome-4.12.6\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:19:25)
    at c:\Users\danie\.vscode\extensions\msjsdiag.debugger-for-chrome-4.12.6\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:58:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

### Steps To Reproduce
1. Create Divi Extension, like it's explained here: [https://github.com/elegantthemes/create-divi-extension#create-divi-extension-](url)

2. Edit launch.json, like it's explained here: [https://github.com/elegantthemes/create-divi-extension/blob/master/packages/divi-scripts/template/README.md#visual-studio-code](url)

3. Run "npm start build" in plugin folder

4. Set breakpoint in frontend.js

### vs-chrome-debug.txt
[vscode-chrome-debug.txt](https://github.com/elegantthemes/create-divi-extension/files/4527837/vscode-chrome-debug.txt)

**Comment by lanresmith** [comment]
Please be informed that you can either run `npm start` or `npm build`, not `npm start build`.
