### ISSUE TITLE
divi-scripts tried to access postcss, but it isn't declared in its dependencies

### ISSUE THREAD

**Issue by solybarr** [elegantthemes/create-divi-extension#402]
### Problem Description
Get an error message => Error: divi-scripts tried to access postcss, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

I tried adding postcss as a dependency in divi-scripts/package.json but its not making any difference. Thanks for any help.
This module has no problems when using "yarn start".

### Steps To Reproduce
1. go into module folder
2. run yarn zip

### Error message
helios@Sols-iMac new-module % yarn zip
/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:28604
    throw firstError;
    ^

Error: divi-scripts tried to access postcss, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: postcss (via "postcss")
Required by: divi-scripts@npm:1.0.2-rc.0 (via /Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.yarn/cache/divi-scripts-npm-1.0.2-rc.0-c3cbab4ed2-8254bd17c1.zip/node_modules/divi-scripts/scripts/)

Require stack:
- /Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.yarn/cache/divi-scripts-npm-1.0.2-rc.0-c3cbab4ed2-8254bd17c1.zip/node_modules/divi-scripts/scripts/build.js
    at internalTools_makeError (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:28349:34)
    at resolveToUnqualified (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:29282:21)
    at resolveRequest (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:29368:29)
    at Object.resolveRequest (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:29434:26)
    at Function.external_module_.Module._resolveFilename (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:28581:34)
    at Function.external_module_.Module._load (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:28445:48)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.yarn/cache/divi-scripts-npm-1.0.2-rc.0-c3cbab4ed2-8254bd17c1.zip/node_modules/divi-scripts/scripts/build.js:46:17)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.external_module_.Module._load (/Users/helios/Local Sites/opening-times/app/public/wp-content/plugins/new-module/.pnp.js:28477:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by lanresmith** [comment]
Hi @solybarr can you please confirm if you're using the latest version of CDE? I'm unable to reproduce this error with the latest version & postcss is declared as a dependency for divi-scripts.
