### ISSUE TITLE
Yarn build fails if project has the word "fields" in its absolute path

### ISSUE THREAD

**Issue by NaimNaimov** [elegantthemes/create-divi-extension#411]
### Problem Description

Yarn build fails, if the absolute path to the extension has the word "fields" in it - notice the parent directory name **foofields** in the example below:

```
$ yarn build
yarn run v1.22.4
$ divi-scripts build
Creating an optimized production build...
fs.js:125
    throw err;
    ^

Error: ENOENT: no such file or directory, open '[MY_PROJECT_PATH]\foofields\my-extension\styles\style.min.css'
    at Object.openSync (fs.js:454:3)
    at Object.readFileSync (fs.js:354:35)
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\divi-scripts\scripts\build.js:169:22
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\webpack\lib\Compiler.js:265:13
    at Compiler.emitRecords ([MY_PROJECT_PATH]\foofields\my-extension\node_modules\webpack\lib\Compiler.js:371:38)
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\webpack\lib\Compiler.js:258:10
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\webpack\lib\Compiler.js:364:12
    at next ([MY_PROJECT_PATH]\foofields\my-extension\node_modules\tapable\lib\Tapable.js:218:11)
    at Compiler.<anonymous> ([MY_PROJECT_PATH]\foofields\my-extension\node_modules\webpack\lib\performance\SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 ([MY_PROJECT_PATH]\foofields\my-extension\node_modules\tapable\lib\Tapable.js:222:13)
    at Compiler.afterEmit ([MY_PROJECT_PATH]\foofields\my-extension\node_modules\webpack\lib\Compiler.js:361:9)
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\webpack\lib\Compiler.js:350:15
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\async\dist\async.js:473:16
    at iteratorCallback ([MY_PROJECT_PATH]\foofields\my-extension\node_modules\async\dist\async.js:1064:13)
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\async\dist\async.js:969:16
    at [MY_PROJECT_PATH]\foofields\my-extension\node_modules\graceful-fs\graceful-fs.js:61:14
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The issue stems from this specific webpack configuration rule:

```
{
    test: /\.(s?css|sass)$/,
    exclude: [/\.module\.css$/, /fields/],
    use: extractTextPluginFrontend.extract(
    // ...
```

Webpack rule tests are ran against absolute filepaths and thus the `/fields/` exclusion regex leads to modules' style.css file not being bundled correctly.

### Steps To Reproduce

1. `mkdir foofields`
2. `cd foofields`
3. `npx create-divi-extension my-extension`
4. `cd my-extension`
5. `yarn build`

P.S @atanas-dev says hi :)
____
### Attached PR
* https://github.com/elegantthemes/create-divi-extension/pull/417

**Comment by lanresmith** [comment]
Thanks @NaimNaimov for spotting that. This is now fixed in https://github.com/elegantthemes/create-divi-extension/pull/417
