### ISSUE TITLE
npm run zip and yarn zip is failed ... it is returning errors

### ISSUE THREAD

**Issue by hamzahabib2000** [elegantthemes/create-divi-extension#569]
npm run zip and yarn zip is failed ... it is returning errors ... also tried with yarn commands ...
I'm using nvm ... and tried the following node version:
v12.0.0
v13.0.0
v13.14.0
v14.0.0

Built the bundle with browser support for >1%, last 4 versions, Firefox ESR, not ie < 11.
fs.js:125
throw err;
^
Error: EPERM: operation not permitted, symlink 'D:\apachehtdocs\divi\wp-content\plugins\divi3\node_modules\divi-scripts\config\Gruntfile.js' -> 'D:\apachehtdocs\divi\wp-content\plugins\divi3\Gruntfile.js'
at Object.symlinkSync (fs.js:962:3)
at Object. (D:\apachehtdocs\divi\wp-content\plugins\divi3\node_modules\divi-scripts\scripts\zip.js:34:4)
at Module._compile (internal/modules/cjs/loader.js:759:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
at Module.load (internal/modules/cjs/loader.js:628:32)
at Function.Module._load (internal/modules/cjs/loader.js:555:12)
at Function.Module.runMain (internal/modules/cjs/loader.js:826:10)
at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! divi3@0.1.0 zip: divi-scripts build && divi-scripts zip
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the divi3@0.1.0 zip script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\hamza\AppData\Roaming\npm-cache_logs\2022-05-22T15_52_24_149Z-debug.log

**Comment by lanresmith** [comment]
@hamzahabib2000 The error message suggests there's a filesystem or user permission problem. Seems you're on Windows, right? Can you please first run `cmd` as admin & then run `yarn zip`?
