### ISSUE TITLE
'create-divi-extension' fails to create the divi extension. 

### ISSUE THREAD

**Issue by Sim-Says** [elegantthemes/create-divi-extension#617]
### Problem Description
'create-divi-extension' fails to create the divi extension. 

See the error log below:
---------------------------
F:\MAMP\htdocs\website1>npx create-divi-extension /wp-content/plugins/my-login

Creating a new Divi extension in F:\wp-content\plugins\my-login.

Installing packages. This might take a couple of minutes.
Installing react, react-dom, and divi-scripts...

➤ YN0000: ┌ Resolution step
➤ YN0061: │ fsevents@npm:1.1.3 is deprecated: fsevents 1 will break on node v14+ and could be using ins.
➤ YN0061: │ eslint-loader@npm:1.9.0 is deprecated: This loader has been deprecated. Please use eslint-w
➤ YN0061: │ extract-text-webpack-plugin@npm:3.0.2 is deprecated: Deprecated. Please use https://github.plugin
➤ YN0013: │ grunt-po2mo@https://github.com/elegantthemes/grunt-po2mo.git#commit=26eca7c892db50837b58fdc
➤ YN0061: │ babel-eslint@npm:8.2.2 is deprecated: babel-eslint is now @babel/eslint-parser. This packag
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.23.3 is no longer maintained and not recommendues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown ued. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual versio
➤ YN0061: │ browserslist@npm:2.11.3 is deprecated: Browserslist 2 could fail on reading Browserslist >3
➤ YN0061: │ svgo@npm:1.3.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0061: │ node-pre-gyp@npm:0.6.39 is deprecated: Please upgrade to @mapbox/node-pre-gyp: the non-scop and only the @mapbox scoped package will recieve updates in the future
➤ YN0032: │ nan@npm:2.17.0: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ uglify-es@npm:3.3.10 is deprecated: support for ECMAScript is superseded by `uglify-js` as 
➤ YN0032: │ iltorb@npm:2.4.5: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ iltorb@npm:2.4.5 is deprecated: The zlib module provides APIs for brotli compression/decomp0, please use it over iltorb
➤ YN0061: │ html-webpack-plugin@npm:2.30.1 is deprecated: out of support
➤ YN0061: │ stable@npm:0.1.8 is deprecated: Modern JS already guarantees Array#sort() is a stable sort,he compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Globallity
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/reque
➤ YN0061: │ request@npm:2.81.0 is deprecated: request has been deprecated, see https://github.com/reque
➤ YN0061: │ hawk@npm:3.1.3 is deprecated: This module moved to @hapi/hawk. Please make sure to switch o supported and may contain bugs and critical security issues.
➤ YN0061: │ browserslist@npm:1.7.7 is deprecated: Browserslist 2 could fail on reading Browserslist >3.
➤ YN0061: │ tar@npm:2.2.2 is deprecated: This version of tar is no longer supported, and will not receisap.
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. 
dependencies
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using in
2.
➤ YN0061: │ sntp@npm:1.0.9 is deprecated: This module moved to @hapi/sntp. Please make sure to switch o supported and may contain bugs and critical security issues.
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0061: │ har-validator@npm:4.2.1 is deprecated: this library is no longer supported
➤ YN0061: │ cryptiles@npm:2.0.5 is deprecated: This version has been deprecated in accordance with the . Please upgrade to the latest version to get the best features, bug fixes, and security patches. If yo paid support is available for older versions (hapi.im/commercial).
➤ YN0061: │ boom@npm:2.10.1 is deprecated: This version has been deprecated in accordance with the hapiease upgrade to the latest version to get the best features, bug fixes, and security patches. If you ard support is available for older versions (hapi.im/commercial).
➤ YN0061: │ hoek@npm:2.16.3 is deprecated: This version has been deprecated in accordance with the hapiease upgrade to the latest version to get the best features, bug fixes, and security patches. If you ard support is available for older versions (hapi.im/commercial).
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may unces, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ svgo@npm:0.7.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ @npmcli/move-file@npm:2.0.1 is deprecated: This functionality has been moved to @npmcli/fs
➤ YN0061: │ request-promise-native@npm:1.0.9 is deprecated: request-promise-native has been deprecated  request package, see https://github.com/request/request/issues/3142
➤ YN0061: │ circular-json@npm:0.3.3 is deprecated: CircularJSON is in maintenance only, flatted is its 
➤ YN0061: │ sane@npm:4.1.0 is deprecated: some dependency vulnerabilities fixed, support for node < 10 features added
➤ YN0061: │ flatten@npm:1.0.3 is deprecated: flatten is deprecated in favor of utility frameworks such 
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolv
➤ YN0061: │ w3c-hr-time@npm:1.0.2 is deprecated: Use your platform's native performance.now() and perfo
➤ YN0061: │ source-map-url@npm:0.4.1 is deprecated: See https://github.com/lydell/source-map-url#deprec
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ acorn-dynamic-import@npm:2.0.2 is deprecated: This is probably built in to whatever tool yodk
➤ YN0061: │ querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code shoad.
➤ YN0032: │ evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
➤ YN0002: │ babel-plugin-transform-dynamic-import@npm:2.0.0 doesn't provide @babel/core (pc1ef2), requeimport
➤ YN0060: │ divi-scripts@npm:1.0.2-rc.0 provides @babel/core (p65604) with version 7.0.0-beta.42, whichmed-asset-import requests
➤ YN0060: │ divi-scripts@npm:1.0.2-rc.0 provides grunt (p1dbcd) with version 1.0.2, which doesn't satis
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for dr p-prefixed code
➤ YN0000: └ Completed in 38s 257ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yargs@npm:15.4.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:3.10.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:6.6.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:8.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ zip-stream@npm:1.2.0 can't be found in the cache and will be fetched from the remote regist
➤ YN0000: └ Completed in 42s 746ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0007: │ core-js@npm:2.6.12 must be built because it never has been before or the last one failed
➤ YN0000: Done with warnings in 7m 10s

Aborting installation.
Unexpected error. Please report it as a bug:
Error: Cannot find module 'F:\wp-content\plugins\my-login\node_modules\divi-scripts\package.json'      
Require stack:
- C:\Users\Jose\AppData\Local\npm-cache\_npx\e6ceb1c4e2cebb75\node_modules\create-divi-extension\createDiviExtension.js
- C:\Users\Jose\AppData\Local\npm-cache\_npx\e6ceb1c4e2cebb75\node_modules\create-divi-extension\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at checkNodeVersion (C:\Users\Jose\AppData\Local\npm-cache\_npx\e6ceb1c4e2cebb75\node_modules\create-divi-extension\createDiviExtension.js:552:23)
    at C:\Users\Jose\AppData\Local\npm-cache\_npx\e6ceb1c4e2cebb75\node_modules\create-divi-extension\createDiviExtension.js:340:7
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Jose\\AppData\\Local\\npm-cache\\_npx\\e6ceb1c4e2cebb75\\node_modules\\create-divi-extension\\createDiviExtension.js',
    'C:\\Users\\Jose\\AppData\\Local\\npm-cache\\_npx\\e6ceb1c4e2cebb75\\node_modules\\create-divi-extension\\index.js'
  ]
}

Deleting generated file... package.json
Done.

### Steps To Reproduce
1. Following are the installed package versions
         F:\MAMP\htdocs\website1>node -v
         v14.19.0
         F:\MAMP\htdocs\website1>npm -v
         9.2.0
         F:\MAMP\htdocs\website1>yarn -v
         3.3.1

2. Run the following command :
         npx create-divi-extension /wp-content/plugins/my-login

**Comment by Sim-Says** [comment]
Closing this issue as this issue no longer exists. But a different one reported by others appears.

Solution :
I downgraded the node version to v12.13.0 using nvm.

After downgrade the following Error occurs which is also reported as issue#616:
error An unexpected error occurred: "https://raw.githubusercontent.com/elegantthemes/grunt-po2mo/26eca7c892db50837b58fdcf3771c5eb331a2ead/package.json: connect ETIMEDOUT 49.44.79.236:443".
